FROM centos:centos6
MAINTAINER me@summernguyen.net



RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf

RUN yum clean all 
RUN yum install -y ruby-devel gcc rsync rpm-build rubygems
RUN gem install fpm


